version: "3.7"
services:
  spark-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
    ports:
      - 8888:8888
